export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Chiron Sung HK",
  "Linefont",
  "Material Icons",
  "Material Icons Round",
  "Material Icons Outlined",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols Outlined",
  "Material Symbols",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AR Guides",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC Guides",
  "Playwrite AU VIC",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA Guides",
  "Playwrite CA",
  "Playwrite CL",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CU Guides",
  "Playwrite CU",
  "Playwrite CZ",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE LA",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS Guides",
  "Playwrite DE SAS",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DE Grund Guides",
  "Playwrite DK Uloopet",
  "Playwrite ES",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite ES Deco Guides",
  "Playwrite ES Deco",
  "Playwrite FR Trad",
  "Playwrite FR Moderne Guides",
  "Playwrite GB J",
  "Playwrite FR Trad Guides",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite HR Guides",
  "Playwrite HR",
  "Playwrite GB S Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite HR Lijeva",
  "Playwrite HU Guides",
  "Playwrite ID Guides",
  "Playwrite ID",
  "Playwrite IE",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite HU",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IE Guides",
  "Playwrite IT Trad",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO Guides",
  "Playwrite NZ",
  "Playwrite NO",
  "Playwrite NZ Basic Guides",
  "Playwrite PE",
  "Playwrite NZ Basic",
  "Playwrite NZ Guides",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite IT Trad Guides",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite SK",
  "Playwrite RO Guides",
  "Playwrite AU QLD",
  "Playwrite SK Guides",
  "Playwrite TZ Guides",
  "Playwrite TZ",
  "Playwrite US Modern",
  "Playwrite US Trad",
  "Playwrite US Trad Guides",
  "Playwrite US Modern Guides",
  "Playwrite VN Guides",
  "Playwrite VN",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite IT Moderna Guides",
  "Wavefont"
];