export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols Rounded",
  "Material Symbols Outlined",
  "Material Symbols Sharp",
  "Material Symbols",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU SA Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite BE VLG",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CU",
  "Playwrite CL",
  "Playwrite CU Guides",
  "Playwrite CZ",
  "Playwrite DE LA Guides",
  "Playwrite DE Grund Guides",
  "Playwrite CZ Guides",
  "Playwrite DE LA",
  "Playwrite DE Grund",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite DK Loopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite ES Guides",
  "Playwrite AT Guides",
  "Playwrite FR Trad",
  "Playwrite GB S Guides",
  "Playwrite GB S",
  "Playwrite GB J",
  "Playwrite HR Guides",
  "Playwrite HR",
  "Playwrite GB J Guides",
  "Playwrite HR Lijeva",
  "Playwrite FR Trad Guides",
  "Playwrite HU",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU Guides",
  "Playwrite ID Guides",
  "Playwrite IE Guides",
  "Playwrite IE",
  "Playwrite ID",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IN",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite IT Moderna",
  "Playwrite IT Trad Guides",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite MX",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO Guides",
  "Playwrite NG Modern Guides",
  "Playwrite NO",
  "Playwrite NZ Guides",
  "Playwrite NZ Basic",
  "Playwrite NZ",
  "Playwrite PE Guides",
  "Playwrite PL Guides",
  "Playwrite PL",
  "Playwrite NZ Basic Guides",
  "Playwrite PE",
  "Playwrite PT",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite PT Guides",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite TZ Guides",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite SK",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite US Trad Guides",
  "Playwrite US Trad",
  "Wavefont"
];