export const incompatibleFonts = [
  "Allkin",
  "Chiron Sung HK",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons",
  "Material Symbols Rounded",
  "Material Symbols Outlined",
  "Material Symbols Sharp",
  "Material Symbols",
  "Material Icons Two Tone",
  "Playwrite AR",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS Guides",
  "Playwrite AU TAS",
  "Playwrite AU VIC",
  "Playwrite BE VLG",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite AR Guides",
  "Playwrite CL Guides",
  "Playwrite CL",
  "Playwrite CO Guides",
  "Playwrite CU Guides",
  "Playwrite CU",
  "Playwrite CO",
  "Playwrite CZ Guides",
  "Playwrite CZ",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DE LA",
  "Playwrite DK Uloopet",
  "Playwrite DE VA",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES Guides",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite ES",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite GB J",
  "Playwrite FR Trad",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR",
  "Playwrite FR Trad Guides",
  "Playwrite HU",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IS",
  "Playwrite IN Guides",
  "Playwrite IS Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Trad",
  "Playwrite MX Guides",
  "Playwrite IT Trad Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite NZ",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Guides",
  "Playwrite PE Guides",
  "Playwrite PE",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite RO",
  "Playwrite PT",
  "Playwrite RO Guides",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite SK",
  "Playwrite US Modern",
  "Playwrite TZ Guides",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite US Trad Guides",
  "Playwrite VN",
  "Playwrite ZA",
  "Playwrite VN Guides",
  "Playwrite ZA Guides",
  "Playwrite AT",
  "Playwrite MX",
  "Playwrite PT Guides",
  "Wavefont"
];