import {build} from 'bun';
import path from 'path';

if (process.env.NODE_ENV !== 'production') {
	throw new Error('This script must be run using NODE_ENV=production');
}

console.time('Generated.');

// Read sandbox scripts as text and generate modules that export them as strings
const scripts = [
	{name: 'render-video-script', file: 'src/scripts/render-video.ts'},
	{name: 'render-still-script', file: 'src/scripts/render-still.ts'},
	{name: 'ensure-browser-script', file: 'src/scripts/ensure-browser.ts'},
];

for (const script of scripts) {
	const content = await Bun.file(script.file).text();
	const escaped = content.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('$', '\\$');
	const moduleContent = `// Generated by bundle.ts - do not edit manually\nexport const script = \`${escaped}\`;\n`;
	await Bun.write(`src/internals/${script.name}.ts`, moduleContent);
}

const output = await build({
	entrypoints: ['src/index.ts'],
	naming: '[name].mjs',
	target: 'node',
	external: [
		'remotion',
		'remotion/no-react',
		'remotion/version',
		'@vercel/sandbox',
		'@vercel/blob',
	],
});

if (!output.success) {
	console.log(output.logs.join('\n'));
	process.exit(1);
}

for (const file of output.outputs) {
	const str = await file.text();
	const out = path.join('dist', 'esm', file.path);

	await Bun.write(out, str);
}

console.timeEnd('Generated.');
